version: '2'
services:
    vestdesk-app:
        image: vestdesk
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://vestdesk-mysql:3306/vestdesk?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    vestdesk-mysql:
        extends:
            file: mysql.yml
            service: vestdesk-mysql
